export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan' }, { code: 'AL', name: 'Albania' }, { code: 'DZ', name: 'Algeria' },
  { code: 'AD', name: 'Andorra' }, { code: 'AO', name: 'Angola' }, { code: 'AG', name: 'Antigua and Barbuda' },
  { code: 'AR', name: 'Argentina' }, { code: 'AM', name: 'Armenia' }, { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' }, { code: 'AZ', name: 'Azerbaijan' }, { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' }, { code: 'BD', name: 'Bangladesh' }, { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' }, { code: 'BE', name: 'Belgium' }, { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' }, { code: 'BT', name: 'Bhutan' }, { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' }, { code: 'BW', name: 'Botswana' }, { code: 'BR', name: 'Brazil' },
  { code: 'BN', name: 'Brunei' }, { code: 'BG', name: 'Bulgaria' }, { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' }, { code: 'CV', name: 'Cabo Verde' }, { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' }, { code: 'CA', name: 'Canada' }, { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' }, { code: 'CL', name: 'Chile' }, { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' }, { code: 'KM', name: 'Comoros' }, { code: 'CD', name: 'Congo, Democratic Republic of the' },
  { code: 'CG', name: 'Congo, Republic of the' }, { code: 'CR', name: 'Costa Rica' }, { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' }, { code: 'CY', name: 'Cyprus' }, { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' }, { code: 'DJ', name: 'Djibouti' }, { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' }, { code: 'EC', name: 'Ecuador' }, { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' }, { code: 'GQ', name: 'Equatorial Guinea' }, { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' }, { code: 'SZ', name: 'Eswatini' }, { code: 'ET', name: 'Ethiopia' },
  { code: 'FJ', name: 'Fiji' }, { code: 'FI', name: 'Finland' }, { code: 'FR', name: 'France' },
  { code: 'GA', name: 'Gabon' }, { code: 'GM', name: 'Gambia' }, { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' }, { code: 'GH', name: 'Ghana' }, { code: 'GR', name: 'Greece' },
  { code: 'GD', name: 'Grenada' }, { code: 'GT', name: 'Guatemala' }, { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' }, { code: 'GY', name: 'Guyana' }, { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' }, { code: 'HU', name: 'Hungary' }, { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' }, { code: 'ID', name: 'Indonesia' }, { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' }, { code: 'IE', name: 'Ireland' }, { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' }, { code: 'JM', name: 'Jamaica' }, { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' }, { code: 'KZ', name: 'Kazakhstan' }, { code: 'KE', name: 'Kenya' },
  { code: 'KI', name: 'Kiribati' }, { code: 'KP', name: 'North Korea' }, { code: 'KR', name: 'South Korea' },
  { code: 'KW', name: 'Kuwait' }, { code: 'KG', name: 'Kyrgyzstan' }, { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' }, { code: 'LB', name: 'Lebanon' }, { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' }, { code: 'LY', name: 'Libya' }, { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' }, { code: 'LU', name: 'Luxembourg' }, { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' }, { code: 'MY', name: 'Malaysia' }, { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' }, { code: 'MT', name: 'Malta' }, { code: 'MH', name: 'Marshall Islands' },
  { code: 'MR', name: 'Mauritania' }, { code: 'MU', name: 'Mauritius' }, { code: 'MX', name: 'Mexico' },
  { code: 'FM', name: 'Micronesia' }, { code: 'MD', name: 'Moldova' }, { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' }, { code: 'ME', name: 'Montenegro' }, { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' }, { code: 'MM', name: 'Myanmar' }, { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' }, { code: 'NP', name: 'Nepal' }, { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' }, { code: 'NI', name: 'Nicaragua' }, { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' }, { code: 'MK', name: 'North Macedonia' }, { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' }, { code: 'PK', name: 'Pakistan' }, { code: 'PW', name: 'Palau' },
  { code: 'PA', name: 'Panama' }, { code: 'PG', name: 'Papua New Guinea' }, { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' }, { code: 'PH', name: 'Philippines' }, { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' }, { code: 'QA', name: 'Qatar' }, { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' }, { code: 'RW', name: 'Rwanda' }, { code: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LC', name: 'Saint Lucia' }, { code: 'VC', name: 'Saint Vincent and the Grenadines' }, { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' }, { code: 'ST', name: 'Sao Tome and Principe' }, { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' }, { code: 'RS', name: 'Serbia' }, { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' }, { code: 'SG', name: 'Singapore' }, { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' }, { code: 'SB', name: 'Solomon Islands' }, { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' }, { code: 'SS', name: 'South Sudan' }, { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' }, { code: 'SD', name: 'Sudan' }, { code: 'SR', name: 'Suriname' },
  { code: 'SE', name: 'Sweden' }, { code: 'CH', name: 'Switzerland' }, { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' }, { code: 'TJ', name: 'Tajikistan' }, { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' }, { code: 'TL', name: 'Timor-Leste' }, { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' }, { code: 'TT', name: 'Trinidad and Tobago' }, { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' }, { code: 'TM', name: 'Turkmenistan' }, { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' }, { code: 'UA', name: 'Ukraine' }, { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' }, { code: 'US', name: 'United States' }, { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' }, { code: 'VU', name: 'Vanuatu' }, { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' }, { code: 'YE', name: 'Yemen' }, { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' }
];

export const COUNTRY_SPECIFIC_CONTENT = {
  US: [
    { id: 1, title: "US Voter Registration", details: "In the US, you must be a citizen and 18 by Election Day. Most states require registration weeks in advance, though some offer same-day registration.", fact: "Did you know? You can register to vote at the DMV in most states thanks to the 'Motor Voter' act." },
    { id: 3, title: "Primary Elections", details: "Before the general election, states hold Primaries or Caucuses to choose party nominees for the President and other offices.", fact: "The 'Iowa Caucus' is traditionally the first major contest in the US presidential primary season." },
    { id: 6, title: "Electoral College", details: "The US President is not elected directly. Instead, voters choose 'electors' who then cast votes for the President.", fact: "A candidate can win the popular vote but lose the election due to the Electoral College system." }
  ],
  IN: [
    { id: 1, title: "EPIC Registration", details: "In India, the Election Commission issues an Elector's Photo Identity Card (EPIC). Registration can be done online via the NVSP portal.", fact: "India has the largest electorate in the world, with over 900 million eligible voters." },
    { id: 5, title: "VVPAT Counting", details: "India uses EVMs with Voter Verifiable Paper Audit Trail (VVPAT). This allows voters to verify that their vote was cast correctly.", fact: "The ink used to mark voters' fingers is 'Indelible Ink' which lasts for weeks." },
    { id: 7, title: "Model Code of Conduct", details: "The MCC comes into force immediately after the election schedule is announced, regulating the behavior of parties and candidates.", fact: "No new projects or subsidies can be announced by the government once MCC is in place." }
  ],
  GB: [
    { id: 1, title: "UK Electoral Register", details: "You must be on the electoral register to vote. In the UK, you can register to vote if you are 16 or over (but can't vote until 18).", fact: "The UK uses individual electoral registration rather than household registration." },
    { id: 4, title: "Polling Cards", details: "Before an election, you'll receive a poll card telling you when to vote and at which polling station.", fact: "You don't actually need your poll card to vote, as long as you're on the register." },
    { id: 6, title: "First Past the Post", details: "The UK uses the 'First Past the Post' system for general elections, where the candidate with the most votes in a constituency wins.", fact: "The leader of the party with the most seats in the House of Commons is usually invited by the Monarch to form a government." }
  ]
};

export const GLOBAL_FALLBACK_CONTENT = [
  { id: 1, title: "National Voter Registration", details: "In most democratic nations, citizens must register to vote prior to the election date. This ensures eligibility and prevents voter fraud.", fact: "The registration process and deadlines vary significantly around the world." },
  { id: 4, title: "National Polling Process", details: "On voting day, registered voters cast their ballots at designated polling stations under supervised conditions.", fact: "Many nations employ international observers to ensure the polling process is free and fair." },
  { id: 6, title: "National Election Results", details: "The national electoral commission or equivalent authority counts the votes and officially declares the winners.", fact: "The speed of results declaration depends heavily on whether voting was electronic or paper-based." }
];

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'hi', name: 'Hindi' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'zh', name: '中文' },
  { code: 'ar', name: 'العربية' },
  { code: 'pt', name: 'Português' },
  { code: 'ru', name: 'Русский' },
  { code: 'ja', name: '日本語' }
];

export const TIMELINE_STAGES = [
  {
    id: 1,
    title: "Voter Registration",
    teaser: "The first step to participate.",
    image: "https://picsum.photos/seed/register/800/1200",
    details: "Voter registration is the process where eligible citizens enroll to vote. You must provide proof of age and citizenship. Once registered, you are added to the electoral roll.",
    fact: "Did you know? In many countries, you can register to vote when you get your driver's license.",
    points: ["Check eligibility requirements", "Fill out the application form", "Keep your voter ID safe"]
  },
  {
    id: 2,
    title: "Candidate Nomination",
    teaser: "People step forward to represent you.",
    image: "https://picsum.photos/seed/candidate/800/1200",
    details: "Political parties and independent individuals file their nomination papers. The election commission scrutinizes these to ensure they meet all legal requirements to run for office.",
    fact: "Did you know? Candidates often have to pay a deposit, which they lose if they don't get a minimum percentage of votes.",
    points: ["Filing nomination papers", "Scrutiny of candidates", "Withdrawal period"]
  },
  {
    id: 3,
    title: "Election Campaigning",
    teaser: "Candidates share their vision and promises.",
    image: "https://picsum.photos/seed/campaign/800/1200",
    details: "During this period, candidates organize rallies, debates, and distribute manifestos. It's a time for voters to understand what each candidate stands for before making a decision.",
    fact: "Did you know? Campaigning must officially stop a certain number of hours (often 48) before voting begins. This is called the 'election silence' period.",
    points: ["Read party manifestos", "Attend public debates", "Verify claims and promises"]
  },
  {
    id: 4,
    title: "Voting Day",
    teaser: "Your chance to make your voice heard.",
    image: "https://picsum.photos/seed/voting/800/1200",
    details: "Voters go to designated polling booths, verify their identity, and cast their vote secretly. Every vote has equal value, regardless of the voter's background.",
    fact: "Did you know? The secret ballot system is designed to prevent intimidation and bribery.",
    points: ["Bring valid ID", "Find your polling station", "Cast your vote secretly"]
  },
  {
    id: 5,
    title: "Vote Counting",
    teaser: "Every single vote is carefully tallied.",
    image: "https://picsum.photos/seed/counting/800/1200",
    details: "Under strict security and in the presence of candidate representatives, the votes (electronic or paper) are counted. The process is designed to be highly transparent.",
    fact: "Did you know? EVMs (Electronic Voting Machines) are standalone devices not connected to any network, making them resistant to remote hacking.",
    points: ["Strict security protocols", "Presence of observers", "Transparent tallying"]
  },
  {
    id: 6,
    title: "Results Declaration",
    teaser: "The winners are officially announced.",
    image: "https://picsum.photos/seed/results/800/1200",
    details: "The election commission officially declares the winners based on the count. The candidate with the highest number of votes in a constituency wins.",
    fact: "Did you know? If the margin is extremely close, candidates can legally request a recount.",
    points: ["Official announcement", "Issuing winning certificate", "Accepting the mandate"]
  },
  {
    id: 7,
    title: "Swearing In",
    teaser: "The new leaders take charge.",
    image: "https://picsum.photos/seed/swearingin/800/1200",
    details: "Elected representatives take an oath of office, swearing allegiance to the constitution. This marks the formal beginning of their term in public service.",
    fact: "Did you know? The inauguration date is often fixed by law to ensure a smooth transition of power.",
    points: ["Taking the oath", "Formation of government", "Beginning of official duties"]
  }
];

export const TRANSLATIONS = {
  en: {
    heroTitle: "Your Voice, Your Power",
    heroSubtitle: "Master the art of democracy. Personalized civic education for the next generation of voters.",
    getStarted: "Begin Journey",
    learnMore: "Learn More",
    timeline: "Election Timeline",
    chatAssistant: "AI Civic Assistant",
    quiz: "Test Your Knowledge",
    feedback: "Share Feedback",
    registration: "Registration",
    nomination: "Nomination",
    campaigning: "Campaigning",
    votingDay: "Voting Day",
    counting: "Counting",
    results: "Results",
    inauguration: "Inauguration",
    selectLanguage: "Choose Your Language",
    selectCountry: "Select Your Country",
    enterName: "What's your name?",
    welcome: "Welcome to ElectionIQ",
    onboardingSub: "Your journey to becoming an informed voter starts here.",
    next: "Next",
    back: "Back",
    finish: "Launch Dashboard",
    askAnything: "Ask anything about elections...",
    send: "Send",
    // Stage 1
    stage1_teaser: "The first step to participate.",
    stage1_details: "Voter registration is the process where eligible citizens enroll to vote. You must provide proof of age and citizenship. Once registered, you are added to the electoral roll.",
    stage1_fact: "Did you know? In many countries, you can register to vote when you get your driver's license.",
    // Stage 2
    stage2_teaser: "People step forward to represent you.",
    stage2_details: "Political parties and independent individuals file their nomination papers. The election commission scrutinizes these to ensure they meet all legal requirements to run for office.",
    stage2_fact: "Did you know? Candidates often have to pay a deposit, which they lose if they don't get a minimum percentage of votes.",
    // Stage 3
    stage3_teaser: "Candidates share their vision and promises.",
    stage3_details: "During this period, candidates organize rallies, debates, and distribute manifestos. It's a time for voters to understand what each candidate stands for before making a decision.",
    stage3_fact: "Did you know? Campaigning must officially stop a certain number of hours (often 48) before voting begins. This is called the 'election silence' period."
  },
  hi: {
    heroTitle: "आपकी आवाज़, आपकी शक्ति",
    heroSubtitle: "लोकतंत्र की कला में महारत हासिल करें। मतदाताओं की अगली पीढ़ी के लिए व्यक्तिगत नागरिक शिक्षा।",
    getStarted: "यात्रा शुरू करें",
    learnMore: "अधिक जानें",
    timeline: "चुनाव समयरेखा",
    chatAssistant: "AI नागरिक सहायक",
    quiz: "अपने ज्ञान का परीक्षण करें",
    feedback: "प्रतिक्रिया साझा करें",
    registration: "पंजीकरण",
    nomination: "नामांकन",
    campaigning: "चुनाव प्रचार",
    votingDay: "मतदान का दिन",
    counting: "मतगणना",
    results: "परिणाम",
    inauguration: "शपथ ग्रहण",
    selectLanguage: "अपनी भाषा चुनें",
    selectCountry: "अपना देश चुनें",
    enterName: "आपका नाम क्या है?",
    welcome: "इलेक्शनआईक्यू में आपका स्वागत है",
    onboardingSub: "एक सूचित मतदाता बनने की आपकी यात्रा यहाँ से शुरू होती है।",
    next: "अगला",
    back: "पीछे",
    finish: "डैशबोर्ड लॉन्च करें",
    askAnything: "चुनाव के बारे में कुछ भी पूछें...",
    send: "भेजें",
    // Stage 1
    stage1_teaser: "भागीदारी के लिए पहला कदम।",
    stage1_details: "मतदाता पंजीकरण वह प्रक्रिया है जहाँ पात्र नागरिक मतदान के लिए नामांकन करते हैं। आपको आयु और नागरिकता का प्रमाण देना होगा। एक बार पंजीकृत होने के बाद, आपको मतदाता सूची में जोड़ दिया जाता है।",
    stage1_fact: "क्या आप जानते हैं? कई देशों में, जब आप अपना ड्राइविंग लाइसेंस प्राप्त करते हैं तो आप मतदान के लिए पंजीकरण कर सकते हैं।",
    // Stage 2
    stage2_teaser: "लोग आपका प्रतिनिधित्व करने के लिए आगे आते हैं।",
    stage2_details: "राजनीतिक दल और स्वतंत्र व्यक्ति अपने नामांकन पत्र दाखिल करते हैं। चुनाव आयोग यह सुनिश्चित करने के लिए इनकी जांच करता है कि वे पद के लिए चुनाव लड़ने की सभी कानूनी आवश्यकताओं को पूरा करते हैं।",
    stage2_fact: "क्या आप जानते हैं? उम्मीदवारों को अक्सर एक जमा राशि का भुगतान करना पड़ता है, जिसे वे खो देते हैं यदि उन्हें न्यूनतम प्रतिशत वोट नहीं मिलते हैं।",
    // Stage 3
    stage3_teaser: "उम्मीदवार अपनी दृष्टि और वादे साझा करते हैं।",
    stage3_details: "इस अवधि के दौरान, उम्मीदवार रैलियां, बहस आयोजित करते हैं और घोषणापत्र वितरित करते हैं। यह मतदाताओं के लिए निर्णय लेने से पहले यह समझने का समय है कि प्रत्येक उम्मीदवार किसके लिए खड़ा है।",
    stage3_fact: "क्या आप जानते हैं? मतदान शुरू होने से एक निश्चित संख्या में घंटों (अक्सर 48) पहले प्रचार आधिकारिक तौर पर बंद हो जाना चाहिए। इसे 'चुनाव मौन' अवधि कहा जाता है।"
  },
  es: {
    heroTitle: "Tu Voz, Tu Poder",
    heroSubtitle: "Domina el arte de la democracia. Educación cívica personalizada para la próxima generación de votantes.",
    getStarted: "Comenzar Viaje",
    learnMore: "Saber más",
    timeline: "Cronología Electoral",
    chatAssistant: "Asistente Cívico AI",
    quiz: "Pon a prueba tu conocimiento",
    feedback: "Compartir comentarios",
    registration: "Registro",
    nomination: "Nominación",
    campaigning: "Campaña",
    votingDay: "Día de Votación",
    counting: "Conteo",
    results: "Resultados",
    inauguration: "Inauguración",
    selectLanguage: "Elige tu idioma",
    selectCountry: "Selecciona tu país",
    enterName: "¿Cómo te llamas?",
    welcome: "Bienvenido a ElectionIQ",
    onboardingSub: "Tu viaje para convertirte en un votante informado comienza aquí.",
    next: "Siguiente",
    back: "Atrás",
    finish: "Lanzar Tablero",
    askAnything: "Pregunta cualquier cosa sobre las elecciones...",
    send: "Enviar"
  },
  fr: {
    heroTitle: "Votre Voix, Votre Pouvoir",
    heroSubtitle: "Maîtrisez l'art de la démocratie. Éducation civique personnalisée pour la prochaine génération d'électeurs.",
    getStarted: "Commencer le voyage",
    learnMore: "En savoir plus",
    timeline: "Calendrier électoral",
    chatAssistant: "Assistant civique IA",
    quiz: "Testez vos connaissances",
    feedback: "Partager des commentaires",
    registration: "Inscription",
    nomination: "Nomination",
    campaigning: "Campagne",
    votingDay: "Jour de vote",
    counting: "Comptage",
    results: "Résultats",
    inauguration: "Inauguration",
    selectLanguage: "Choisissez votre langue",
    selectCountry: "Sélectionnez votre pays",
    enterName: "Quel est votre nom ?",
    welcome: "Bienvenue sur ElectionIQ",
    onboardingSub: "Votre parcours pour devenir un électeur informé commence ici.",
    next: "Suivant",
    back: "Retour",
    finish: "Lancer le tableau de bord",
    askAnything: "Posez n'importe quelle question sur les élections...",
    send: "Envoyer"
  },
  de: {
    heroTitle: "Ihre Stimme, Ihre Macht",
    heroSubtitle: "Meistern Sie die Kunst der Demokratie. Personalisierte politische Bildung für die nächste Generation von Wählern.",
    getStarted: "Reise beginnen",
    learnMore: "Mehr erfahren",
    timeline: "Wahl-Zeitplan",
    chatAssistant: "KI-Bürgerassistent",
    quiz: "Testen Sie Ihr Wissen",
    feedback: "Feedback teilen",
    registration: "Registrierung",
    nomination: "Nominierung",
    campaigning: "Wahlkampf",
    votingDay: "Wahltag",
    counting: "Zählung",
    results: "Ergebnisse",
    inauguration: "Amtseinführung",
    selectLanguage: "Wähle deine Sprache",
    selectCountry: "Wähle dein Land",
    enterName: "Wie heißt du?",
    welcome: "Willkommen bei ElectionIQ",
    onboardingSub: "Deine Reise zum informierten Wähler beginnt hier.",
    next: "Weiter",
    back: "Zurück",
    finish: "Dashboard starten",
    askAnything: "Frage alles über Wahlen...",
    send: "Senden"
  },
  zh: {
    heroTitle: "你的声音，你的力量",
    heroSubtitle: "掌握民主的艺术。为下一代选民提供的个性化公民教育。",
    getStarted: "开始旅程",
    learnMore: "了解更多",
    timeline: "选举时间表",
    chatAssistant: "人工智能公民助手",
    quiz: "测试你的知识",
    feedback: "分享反馈",
    registration: "登记",
    nomination: "提名",
    campaigning: "竞选活动",
    votingDay: "投票日",
    counting: "计票",
    results: "结果",
    inauguration: "就职典礼",
    selectLanguage: "选择你的语言",
    selectCountry: "选择你的国家",
    enterName: "你叫什么名字？",
    welcome: "欢迎来到 ElectionIQ",
    onboardingSub: "你成为知情选民的旅程从这里开始。",
    next: "下一步",
    back: "返回",
    finish: "启动仪表板",
    askAnything: "询问有关选举的任何问题...",
    send: "发送"
  },
  ar: {
    heroTitle: "صوتك، قوتك",
    heroSubtitle: "أتقن فن الديمقراطية. تعليم مدني مخصص للجيل القادم من الناخبين.",
    getStarted: "ابدأ الرحلة",
    learnMore: "تعلم المزيد",
    timeline: "الجدول الزمني للانتخابات",
    chatAssistant: "مساعد مدني بالذكاء الاصطناعي",
    quiz: "اختبر معرفتك",
    feedback: "شاركنا برأيك",
    registration: "التسجيل",
    nomination: "الترشيح",
    campaigning: "الحملات الانتخابية",
    votingDay: "يوم التصويت",
    counting: "الفرز",
    results: "النتائج",
    inauguration: "التنصيب",
    selectLanguage: "اختر لغتك",
    selectCountry: "اختر بلدك",
    enterName: "ما هو اسمك؟",
    welcome: "مرحباً بك في ElectionIQ",
    onboardingSub: "رحلتك لتصبح ناخباً مطّلعاً تبدأ من هنا.",
    next: "التالي",
    back: "رجوع",
    finish: "ابدأ لوحة التحكم",
    askAnything: "اسأل أي شيء عن الانتخابات...",
    send: "إرسال",
    // Stage 1
    stage1_teaser: "الخطوة الأولى للمشاركة.",
    stage1_details: "تسجيل الناخبين هو العملية التي يقوم من خلالها المواطنون المؤهلون بالتسجيل للتصويت. يجب تقديم إثبات السن والمواطنة. بمجرد التسجيل، يتم إضافتك إلى القائمة الانتخابية.",
    stage1_fact: "هل تعلم؟ في العديد من البلدان، يمكنك التسجيل للتصويت عند الحصول على رخصة القيادة الخاصة بك.",
    // Stage 2
    stage2_teaser: "أشخاص يتقدمون لتمثيلك.",
    stage2_details: "تقوم الأحزاب السياسية والأفراد المستقلون بتقديم أوراق ترشيحهم. تقوم لجنة الانتخابات بفحصها للتأكد من استيفائهم لجميع المتطلبات القانونية للترشح للمنصب.",
    stage2_fact: "هل تعلم؟ غالباً ما يتعين على المرشحين دفع تأمين، يفقدونه إذا لم يحصلوا على حد أدنى من الأصوات.",
    // Stage 3
    stage3_teaser: "المرشحون يشاركون رؤيتهم ووعودهم.",
    stage3_details: "خلال هذه الفترة، ينظم المرشحون مسيرات ومناظرات ويوزعون البيانات الانتخابية. إنه وقت للناخبين لفهم ما يمثله كل مرشح قبل اتخاذ القرار.",
    stage3_fact: "هل تعلم؟ يجب أن يتوقف الحملات الانتخابية رسمياً قبل عدد معين من الساعات (غالباً 48) من بدء التصويت. تسمى هذه الفترة 'الصمت الانتخابي'."
  },
  pt: {
    heroTitle: "Sua Voz, Seu Poder",
    heroSubtitle: "Domine a arte da democracia. Educação cívica personalizada para a próxima geração de eleitores.",
    getStarted: "Começar Jornada",
    learnMore: "Saiba mais",
    timeline: "Cronograma Eleitoral",
    chatAssistant: "Assistente Cívico IA",
    quiz: "Teste seu conhecimento",
    feedback: "Compartilhar Feedback",
    registration: "Registro",
    nomination: "Nomeação",
    campaigning: "Campanha",
    votingDay: "Dia da Votação",
    counting: "Contagem",
    results: "Resultados",
    inauguration: "Inauguração",
    selectLanguage: "Escolha seu idioma",
    selectCountry: "Selecione seu país",
    enterName: "Qual é o seu nome?",
    welcome: "Bem-vindo ao ElectionIQ",
    onboardingSub: "Sua jornada para se tornar um eleitor informado começa aqui.",
    next: "Próximo",
    back: "Voltar",
    finish: "Iniciar Painel",
    askAnything: "Pergunte qualquer coisa sobre eleições...",
    send: "Enviar"
  },
  ru: {
    heroTitle: "Ваш голос — ваша сила",
    heroSubtitle: "Овладейте искусством демократии. Персонализированное гражданское образование для следующего поколения избирателей.",
    getStarted: "Начать путешествие",
    learnMore: "Узнать больше",
    timeline: "График выборов",
    chatAssistant: "ИИ-помощник",
    quiz: "Проверьте свои знания",
    feedback: "Поделиться отзывом",
    registration: "Регистрация",
    nomination: "Выдвижение",
    campaigning: "Агитация",
    votingDay: "День голосования",
    counting: "Подсчет",
    results: "Результаты",
    inauguration: "Инаугурация",
    selectLanguage: "Выберите язык",
    selectCountry: "Выберите страну",
    enterName: "Как вас зовут?",
    welcome: "Добро пожаловать в ElectionIQ",
    onboardingSub: "Ваш путь к информированному избирателю начинается здесь.",
    next: "Далее",
    back: "Назад",
    finish: "Запустить панель",
    askAnything: "Спрашивайте что угодно о выборах...",
    send: "Отправить"
  },
  ja: {
    heroTitle: "あなたの声、あなたの力",
    heroSubtitle: "民主主義の技術を習得しましょう。次世代の有権者のためのパーソナライズされた主権者教育。",
    getStarted: "ジャーニーを開始",
    learnMore: "詳しく知る",
    timeline: "選挙タイムライン",
    chatAssistant: "AIシビックアシスタント",
    quiz: "知識をテストする",
    feedback: "フィードバックを共有",
    registration: "登録",
    nomination: "指名",
    campaigning: "選挙運動",
    votingDay: "投票日",
    counting: "開票",
    results: "結果",
    inauguration: "就任式",
    selectLanguage: "言語を選択してください",
    selectCountry: "国を選択してください",
    enterName: "お名前は何ですか？",
    welcome: "ElectionIQへようこそ",
    onboardingSub: "情報に基づいた有権者への道のりがここから始まります。",
    next: "次へ",
    back: "戻る",
    finish: "ダッシュボードを起動",
    askAnything: "選挙について何でも聞いてください...",
    send: "送信"
  }
};

export const STARTER_QUESTIONS = [
  "How do I register to vote?",
  "What happens on voting day?",
  "How are votes counted?",
  "What is the role of the Election Commission?",
  "What if there is a tie?"
];
